server:
  port: 8080
spring:
  application:
    name: "CrediYa_Ms_Autenticacion"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    #include: null
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: Autenticacion
    username: root
    password: P@55w0rd
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    root: INFO
    co.com.pragma.crediya: TRACE
jwt:
  secret: "ZyF3gaQO8sop7Aw1TYlSEBo5atFxxq946345r98tfvfv7i673123r124r43"
  expiration: 3600
  issuer: "Autenticacion"